In [ ]:
!pip install bert4keras==0.7.5

  Created wheel for bert4keras: filename=bert4keras-0.7.5-cp37-none-any.whl size=36496 sha256=c6ac7776289169a8805bfadd7c2973d6b49208e388e059b643f90b189a9ca124
  Stored in directory: /root/.cache/pip/wheels/3d/28/96/9400220273f85d1515b73017f74630d769d6f04523405e2de3
Successfully built bert4keras


In [ ]:
!pip install keras_bert

  Created wheel for keras-bert: filename=keras_bert-0.86.0-cp37-none-any.whl size=34144 sha256=23b4453ae50adc239df48db58565f2e4b661c1dfe0d5e825c9c640f95f2a1649
  Stored in directory: /root/.cache/pip/wheels/66/f0/b1/748128b58562fc9e31b907bb5e2ab6a35eb37695e83911236b
  Created wheel for keras-transformer: filename=keras_transformer-0.38.0-cp37-none-any.whl size=12942 sha256=b49211ad3339c76234c660a625c0028fd3205e434fb652ce5344f4ef50f942e4
  Stored in directory: /root/.cache/pip/wheels/e5/fb/3a/37b2b9326c799aa010ae46a04ddb04f320d8c77c0b7e837f4e
  Created wheel for keras-pos-embd: filename=keras_pos_embd-0.11.0-cp37-none-any.whl size=7554 sha256=7add3f96e24cca2be85d7b70608108f5747e5d2f6c3cc30e3c51a4e6d57691da
  Stored in directory: /root/.cache/pip/wheels/5b/a1/a0/ce6b1d49ba1a9a76f592e70cf297b05c96bc9f418146761032
  Created wheel for keras-multi-head: filename=keras_multi_head-0.27.0-cp37-none-any.whl size=15611 sha256=c4ac8df76e37153725bcd2bbff0f3a07c2b5e0ca2b9b2cd2df5131f67b70c2cc
  Stor

In [ ]:
!pip install tensorflow==2.2

     |████████████████████████████████| 516.2MB 28kB/s 
     |████████████████████████████████| 3.0MB 39.4MB/s 
     |████████████████████████████████| 460kB 50.7MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


Plan1 succeed

In [ ]:
from bert4keras.backend import keras
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
import numpy as np
import json
from keras.models import Model

from bert4keras.backend import keras, K
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
from bert4keras.optimizers import Adam
from bert4keras.snippets import sequence_padding, DataGenerator
from bert4keras.snippets import open
from bert4keras.layers import ConditionalRandomField
from keras.layers import Dense
from keras.models import Model
from tqdm import tqdm
from keras.layers import Dropout, Dense

from keras_bert import extract_embeddings
import tensorflow as tf

config_path = '/content/bert_config.json'
checkpoint_path = tf.train.latest_checkpoint('/content/')
#checkpoint_path = '/content/bert_model.ckpt'
dict_path = '/content/vocab.txt'

def load_data(filename):

    D = []
    with open(filename,encoding='utf-8') as f:
        for l in f:
            l = json.loads(l)
            D.append(l['text'])
    return D

if __name__ == "__main__":


    # 词向量获取方法 cls,mean,
    vector_name = 'cls'
    tokenizer = Tokenizer(dict_path, do_lower_case=True)  # 建立分词器
    model = build_transformer_model(config_path, checkpoint_path)  # 建立模型，加载权重
    maxlen = 70

    # 读取处理数据
    #f1 = 'D:/cluster/data/train.json'
    #res = load_data(f1)
    output = []
    res = result

    print('start to extract vector from BERT: ')

    # 根据提取特征的方法获得词向量
    for r in res:
        token_ids, segment_ids = tokenizer.encode(r,max_length=maxlen)

        if vector_name == 'cls':
            cls_vector = model.predict([np.array([token_ids]), np.array([segment_ids])])[0][0]
            output.append(cls_vector)
        elif vector_name == 'mean':
            new = []
            vector = model.predict([np.array([token_ids]), np.array([segment_ids])])[0]
            for i in range(768):
                temp = 0
                for j in range(len(vector)):
                    temp += vector[j][i]
                new.append(temp/(len(vector)))
            output.append(new)

    print('保存数据')
    np.savetxt("/content/wendy_vector_cls.txt",output)


start to extract vector from BERT: 
保存数据


In [ ]:
count = 0
with open('/content/test_data_annotation.txt',encoding='utf-8') as f:
  for l in f:
    count+=1
print(count)

1083


In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
#显示所有行
pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
#pd.set_option('max_colwidth',500)

In [ ]:
from sklearn.cluster import KMeans
from sklearn.cluster import Birch

#feature = np.loadtxt("/content/bert_vector_cls.txt")
#feature = np.loadtxt("/content/bert_vector_mean.txt")
#feature = np.loadtxt("/content/bert_finetune_vector_cls.txt")
#feature = np.loadtxt("/content/bert_finetune_vector_mean.txt")
#feature = np.loadtxt("/content/bert_finetune260_vector_cls.txt")
#feature = np.loadtxt("/content/bert_finetune390_vector_cls.txt")
feature = np.loadtxt("/content/wendy_vector_cls.txt")
clf = KMeans(n_clusters=8)
s = clf.fit(feature)
kn_pre = clf.predict(feature)

#cluster_assignment = s.labels_
#print(cluster_assignment)

ss = Birch(branching_factor=10, n_clusters = 8, threshold=0.5,compute_labels=True)
birch_pre = ss.fit_predict(feature)
print(kn_pre)
#print(birch_pre)

[4 6 1 7 5 0 2 1 3]


In [ ]:
!pip install hdbscan

In [ ]:
import hdbscan
cluster = hdbscan.HDBSCAN(min_cluster_size=8,metric='euclidean',cluster_selection_method='eom').fit(feature)
cluster_assignment = cluster.labels_
print(cluster_assignment)

[ 1  1  1 ...  1 -1  1]


In [ ]:
print(kn_pre[:1083])
with open("/content/bert_finetune390_cls_kmeans_test.txt",'w') as wf:
  wf.write(str(kn_pre[:1083].tolist()))

[1 7 2 ... 6 4 7]


In [ ]:
print(birch_pre[:1083])
with open("/content/bert_finetune_mean_birch_test.txt",'w') as wf:
  wf.write(str(birch_pre[:1083].tolist()))

[3 2 5 ... 1 0 2]


In [ ]:
print(cluster_assignment[:1083])
with open("/content/bert_finetune_mean_hdbscan_test.txt",'w') as wf:
  wf.write(str(cluster_assignment[:1083].tolist()))

[ 1  1  1 ...  1 -1  1]


Evaluation

In [ ]:
from sklearn import metrics
#kmeans_model = KMeans(n_clusters=8, random_state=1).fit(X)
labels = s.labels_
score = metrics.calinski_harabaz_score(feature,labels)
print(score)

369.84697409965054


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function calinski_harabaz_score is deprecated; Function 'calinski_harabaz_score' has been renamed to 'calinski_harabasz_score' and will be removed in version 0.23.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn import metrics
from sklearn.cluster import KMeans
from sklearn import datasets
# 生成数据集

# 轮廓系数
metrics.silhouette_score(feature,labels, metric='euclidean')

#> 0.5528190123564091

0.03884904321108207

In [ ]:
sklearn.metrics.davies_bouldin_score(feature,labels)

3.5237417364175814

In [ ]:
num_clusters = 8

In [ ]:
clustered_sentences = [[] for i in range(num_clusters)]
for sentence_id, cluster_id in enumerate(kn_pre):
    clustered_sentences[cluster_id].append(res[sentence_id])
for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

Cluster  1
['What might be surprising, for some readers, is to learn that Sarah Grimké is a historical figure, an energetic abolitionist from a slaveholding Charleston family. After moving to Philadelphia and becoming a Quaker, she began speaking publicly against slavery and crusading for women’s rights. With her sister, Angelina, and Angelina’s husband, Theodore Weld, she wrote “American Slavery as It Is,” a “testimony of a thousand witnesses” that influenced Harriet Beecher Stowe’s novel “Uncle Tom’s Cabin,” published 13 years later.']

Cluster  2
['To her credit, Kidd doesn’t insist on a close friendship between these characters. They like each other, but uneasily, Sarah out of guilt and Handful because she knows she’s listed on a household inventory “right after the water trough, the wheelbarrow, the claw hammer and the bushel of flint corn.” Instead, through alternating chapters narrated by Sarah and Handful, spanning 35 years, the novel juxtaposes their experiences of oppression.

In [ ]:
!pip install bert4keras

In [ ]:
!pip install tensorflow==2.2.0

In [ ]:
from bert4keras.backend import keras
from bert4keras.models import build_transformer_model
from bert4keras.tokenizers import Tokenizer
import numpy as np

config_path = '/content/bert_model/bert_config.json'
checkpoint_path = '/content/bert_model/bert_model.ckpt'
dict_path = '/content/bert_model/vocab.txt'

tokenizer = Tokenizer(dict_path, do_lower_case=True)  # 建立分词器
model = build_transformer_model(config_path, checkpoint_path)  # 建立模型，加载权重

# 编码测试
corpus = [
             "Vodafone Wins 20,000 Crore Tax Arbitration Case Against Government",
             "Voda Idea shares jump nearly 15% as Vodafone wins retro tax case in Hague",
             "Gold prices today fall for 4th time in 5 days, down ₹6500 from last month high",
             "Silver futures slip 0.36% to Rs 59,415 per kg, down over 12% this week",
             "Amazon unveils drone that films inside your home. What could go wrong?",
             "IPHONE 12 MINI PERFORMANCE MAY DISAPPOINT DUE TO THE APPLE B14 CHIP",
             "Delhi Capitals vs Chennai Super Kings: Prithvi Shaw shines as DC beat CSK to post second consecutive win in IPL",
             "French Open 2020: Rafael Nadal handed tough draw in bid for record-equaling 20th Grand Slam"
]

#print(corpus)
token_ids, segment_ids = tokenizer.encode(corpus)


print('\n ===== predicting =====\n')

vector = model.predict([np.array([token_ids]), np.array([segment_ids])])
print(vector.shape)



 ===== predicting =====

(1, 8, 768)


In [ ]:
path = 'saved_weights.pt'
model.load_state_dict(torch.load(path))

Plan2 succeed

In [ ]:
!pip install -U sentence-transformers

     |████████████████████████████████| 81kB 5.1MB/s 
     |████████████████████████████████| 2.1MB 15.4MB/s 
     |████████████████████████████████| 1.2MB 50.3MB/s 
     |████████████████████████████████| 901kB 33.2MB/s 
     |████████████████████████████████| 3.3MB 45.9MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-1.1.0-cp37-none-any.whl size=119615 sha256=78afaf8b75ba4cd38f7202c8408a1b692aa8e3f523888657503d52fed24fa04d
  Stored in directory: /root/.cache/pip/wheels/84/cb/21/1066bff3027215c760ca14a198f698bca8fccb92e33e2327eb
Successfully built sentence-transformers


In [ ]:
corpus = [
             "Vodafone Wins 20,000 Crore Tax Arbitration Case Against Government",
             "Voda Idea shares jump nearly 15% as Vodafone wins retro tax case in Hague",
             "Gold prices today fall for 4th time in 5 days, down ₹6500 from last month high",
             "Silver futures slip 0.36% to Rs 59,415 per kg, down over 12% this week",
             "Amazon unveils drone that films inside your home. What could go wrong?",
             "IPHONE 12 MINI PERFORMANCE MAY DISAPPOINT DUE TO THE APPLE B14 CHIP",
             "Delhi Capitals vs Chennai Super Kings: Prithvi Shaw shines as DC beat CSK to post second consecutive win in IPL",
             "French Open 2020: Rafael Nadal handed tough draw in bid for record-equaling 20th Grand Slam"
]

print(corpus)

['Vodafone Wins 20,000 Crore Tax Arbitration Case Against Government', 'Voda Idea shares jump nearly 15% as Vodafone wins retro tax case in Hague', 'Gold prices today fall for 4th time in 5 days, down ₹6500 from last month high', 'Silver futures slip 0.36% to Rs 59,415 per kg, down over 12% this week', 'Amazon unveils drone that films inside your home. What could go wrong?', 'IPHONE 12 MINI PERFORMANCE MAY DISAPPOINT DUE TO THE APPLE B14 CHIP', 'Delhi Capitals vs Chennai Super Kings: Prithvi Shaw shines as DC beat CSK to post second consecutive win in IPL', 'French Open 2020: Rafael Nadal handed tough draw in bid for record-equaling 20th Grand Slam']


In [ ]:
path = "/content/class1.txt"
#path = "/content/test_data_annotation.txt"
import sys
result=[]

with open(path, 'r',encoding='utf8') as f:
  for line in f:
    line = line.replace("\ufeff","")
    result.append(line.strip('\n'))
print(result)

UnicodeDecodeError: ignored

In [ ]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans

embedder = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

corpus_embeddings = embedder.encode(result)
print(corpus_embeddings)

[[ 0.6162678  -0.03353756  0.19717501 ...  0.9555801  -0.5374956
   0.3449843 ]
 [ 0.60900754  0.21543334  0.7866887  ...  0.54325205  0.02599801
  -0.20927729]
 [-0.25242838 -0.1675365   0.8827442  ... -0.01020456 -0.03673603
  -0.17408068]
 ...
 [ 0.07931372  0.7988257   0.55632484 ...  0.72487044 -0.2917974
  -0.20245488]
 [-0.4437512  -0.00811411  0.44895118 ... -0.06891416 -0.14622977
   0.29172873]
 [-0.0593288   0.6054962   0.71759695 ...  0.3600835  -0.7377779
  -0.5549035 ]]


In [ ]:
import numpy as np
np.savetxt("/content/snetence_bert_vector.txt",corpus_embeddings)

In [ ]:
from sklearn.cluster import Birch
ss = Birch(branching_factor=10, n_clusters = 8, threshold=0.5,compute_labels=True)
birch_pre = ss.fit_predict(corpus_embeddings)
print(birch_pre)

[1 3 4 ... 3 0 4]


In [ ]:
!pip install hdbscan

In [ ]:
import hdbscan
cluster = hdbscan.HDBSCAN(min_cluster_size=8,metric='euclidean',cluster_selection_method='eom').fit(corpus_embeddings)
cluster_assignment = cluster.labels_
print(cluster_assignment)

[0 0 0 ... 0 0 0]


In [ ]:
!pip install umap-learn

In [ ]:
import umap
umap_embeddings = umap.UMAP(n_neighbors=8, n_components=5, metric='cosine').fit_transform(corpus_embeddings)
#cluster_assignment = umap_embeddings.labels_
print(umap_embeddings)

In [ ]:
from sklearn.cluster import KMeans
num_clusters = 8
# Define kmeans model
clustering_model = KMeans(n_clusters=num_clusters)
# Fit the embedding with kmeans clustering.
clustering_model.fit(corpus_embeddings)
# Get the cluster id assigned to each news headline.
kn_pre = clustering_model.labels_
print(kn_pre)
kn_centroid = clustering_model.cluster_centers_
print(kn_centroid)

[0 0 1 1 4 3 2 2]
[[ 0.61263764  0.09094789  0.49193186 ...  0.74941605 -0.2557488
   0.0678535 ]
 [ 0.26470578 -0.3152468   0.68221474 ... -0.3334794   0.2840914
   0.05381416]
 [-0.25154     0.29869106  0.58327407 ...  0.14558467 -0.44200385
  -0.1315874 ]
 [ 0.07931371  0.7988257   0.55632484 ...  0.72487044 -0.2917974
  -0.20245488]
 [ 0.5291232   0.2117285   0.02326873 ... -0.4247378   0.33376944
   0.19550073]]


In [ ]:
print(kn_pre[:1083])
with open("/content/sentence_bert_kmeans_test.txt",'w') as wf:
  wf.write(str(kn_pre[:1083].tolist()))
print(birch_pre[:1083])
with open("/content/sentence_bert_birch_test.txt",'w') as wf:
  wf.write(str(birch_pre[:1083].tolist()))
print(cluster_assignment[:1083])
with open("/content/sentence_bert_hdbscan_test.txt",'w') as wf:
  wf.write(str(cluster_assignment[:1083].tolist()))

[7 3 1 ... 3 0 3]
[1 3 4 ... 4 0 1]
[ 0  0  0 ...  0 -1  0]


In [ ]:
with open("/content/bert_finetune260_cls_kmeans_test.txt",'w') as wf:
  wf.write(str(kn_pre[:1083].tolist()))

In [ ]:
from sklearn import metrics
#metrics.calinski_harabaz_score(corpus_embeddings,cluster_assignment)
#metrics.silhouette_score(corpus_embeddings,cluster_assignment, metric='euclidean')
sklearn.metrics.davies_bouldin_score(corpus_embeddings,cluster_assignment)

4.479092815962237

In [ ]:
clustered_sentences = [[] for i in range(num_clusters)]
for sentence_id, cluster_id in enumerate(cluster_assignment):
    clustered_sentences[cluster_id].append(corpus[sentence_id])
for i, cluster in enumerate(clustered_sentences):
    print("Cluster ", i+1)
    print(cluster)
    print("")

annotation的数据来了

In [ ]:
count0 = list(kn_pre[:1083]).count(0)
count1 = list(kn_pre[:1083]).count(1)
count2 = list(kn_pre[:1083]).count(2)
count3 = list(kn_pre[:1083]).count(3)
count4 = list(kn_pre[:1083]).count(4)
count5 = list(kn_pre[:1083]).count(5)
count6 = list(kn_pre[:1083]).count(6)
count7 = list(kn_pre[:1083]).count(7)
print(count0,count1,count2,count3,count4,count5,count6,count7)

0 0 0 0 0 0 0 0


In [ ]:
count0 = list(true_labels).count(0)
count1 = list(true_labels).count(1)
count2 = list(kn_pre[:1083]).count(2)
count3 = list(kn_pre[:1083]).count(3)
count4 = list(kn_pre[:1083]).count(4)
count5 = list(kn_pre[:1083]).count(5)
count6 = list(kn_pre[:1083]).count(6)
count7 = list(kn_pre[:1083]).count(7)
print(count0,count1,count2,count3,count4,count5,count6,count7)

0 0 130 158 158 156 65 204


Purity

In [ ]:
with open("/content/annotation_labels.txt",'r') as f:
  for line in f:
    true_labels = line
print(true_labels)
list_labels = true_labels.split(" ")
print(list_labels)

2 2 3 7 5 5 3 5 6 6 6 6 6 6 6 6 6 6 6 6 3 3 6 6 6 6 3 3 6 6 6 6 6 6 2 2 6 6 6 3 3 2 5 6 6 6 6 7 7 7 7 1 1 1 2 6 6 6 3 6 7 7 7 3 3 4 3 6 6 6 6 6 3 6 6 3 3 3 3 3 7 4 7 7 7 7 8 8 8 8 8 7 7 1 1 1 3 3 3 3 2 2 2 3 2 2 2 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 2 2 2 2 6 6 6 2 3 6 6 6 6 6 7 3 6 6 6 6 6 6 6 6 6 3 3 3 3 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 3 6 6 6 6 6 6 6 6 8 8 1 1 1 3 3 3 2 6 6 6 3 3 3 6 6 6 6 6 6 5 6 6 6 3 3 3 3 6 6 6 6 5 5 5 6 6 5 3 3 7 7 7 6 6 6 6 6 6 6 6 6 3 7 7 7 7 3 3 7 7 8 8 1 1 1 1 1 2 2 2 2 2 3 5 6 6 5 5 6 6 6 6 6 6 6 6 6 3 7 7 7 7 7 7 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 3 6 6 6 7 7 8 1 1 1 2 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 8 8 1 1 1 2 4 4 4 4 4 4 4 7 2 5 6 6 6 6 6 6 8 8 8 8 8 8 8 7 5 7 7 5 5 5 6 6 6 6 6 7 7 7 8 5 5 5 5 7 7 7 7 8 3 7 7 7 7 6 6 6 8 8 8 8 7 8 8 8 7 1 1 1 7 7 4 8 6 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 3 3 3 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 

In [ ]:
with open("/content/bert_finetune_mean_birch_test.txt",'r') as f:
  for line in f:
    line = line.replace(",","")
    line = line.replace("[","")
    true_labels = line.replace("]","")
print(true_labels)
y_pred = true_labels.split(" ")
print(y_pred)

3 2 5 3 6 1 2 1 1 1 0 1 2 7 2 1 7 2 4 2 3 5 1 3 3 2 2 6 5 7 2 3 3 6 3 2 2 3 2 1 6 1 2 3 2 5 5 2 3 0 7 6 7 0 5 5 0 5 1 1 1 5 3 5 5 3 1 5 5 2 3 2 1 5 5 1 3 5 3 1 5 5 2 2 5 2 1 1 1 1 1 1 1 6 0 4 3 3 5 1 5 5 7 2 1 2 5 5 1 1 7 7 5 7 0 0 2 1 4 7 6 5 3 3 3 5 3 3 2 1 6 2 5 6 3 1 3 5 1 6 5 6 3 3 6 1 3 5 2 5 5 1 2 3 3 6 2 5 5 0 0 7 1 3 2 1 1 2 6 0 5 2 3 6 5 2 6 2 3 7 3 2 3 6 3 5 2 7 1 1 3 2 7 6 2 3 3 7 3 3 5 1 7 2 5 1 7 1 5 5 3 6 2 2 2 3 2 1 5 6 0 4 3 5 1 3 3 1 1 5 5 1 7 2 5 2 3 7 1 3 2 1 3 2 3 5 1 3 2 2 3 1 2 3 2 5 1 3 1 1 5 3 1 1 3 5 3 3 1 3 2 1 1 1 1 5 5 2 3 1 2 3 6 2 0 4 5 1 5 1 5 5 5 1 3 1 5 1 3 2 5 1 1 5 6 2 1 3 7 6 2 3 1 2 5 1 3 3 1 1 3 6 1 5 5 5 5 3 5 5 1 7 3 1 3 2 5 6 4 4 5 2 3 5 3 1 3 1 3 6 1 1 3 1 5 1 2 3 6 3 6 3 6 5 1 3 1 0 6 0 0 1 3 3 5 3 3 3 6 2 1 5 1 1 2 2 2 1 3 6 7 1 3 1 3 2 3 5 1 3 3 3 1 2 1 7 0 6 7 6 3 1 7 3 2 1 5 1 3 2 1 1 3 2 3 3 3 7 1 1 3 3 2 2 1 3 1 7 2 4 1 0 3 1 6 7 2 2 2 3 6 1 5 2 7 2 1 5 1 3 7 2 3 3 0 2 5 1 3 1 6 3 2 6 5 7 1 1 7 2 5 2 0 5 0 3 6 3 7 7 5 6 3 3 1 3 5 2 3 6 

In [ ]:
y_pred = kn_pre[:1083]
print(y_pred.tolist())

[7, 3, 1, 3, 1, 7, 7, 2, 4, 1, 0, 5, 0, 6, 1, 4, 2, 5, 0, 1, 7, 7, 4, 4, 5, 2, 7, 6, 4, 2, 2, 7, 7, 2, 2, 3, 7, 3, 0, 4, 2, 1, 2, 4, 3, 4, 4, 2, 7, 6, 6, 0, 0, 0, 5, 5, 6, 4, 7, 4, 7, 5, 3, 1, 4, 5, 7, 5, 7, 3, 4, 3, 2, 7, 7, 7, 5, 7, 7, 5, 7, 7, 0, 6, 7, 5, 3, 3, 7, 5, 7, 2, 5, 0, 0, 0, 7, 3, 4, 4, 3, 3, 0, 2, 4, 6, 2, 7, 4, 4, 2, 4, 4, 4, 2, 6, 1, 3, 6, 6, 2, 4, 0, 1, 1, 4, 1, 5, 7, 4, 3, 5, 3, 0, 4, 4, 0, 4, 3, 4, 3, 3, 7, 5, 0, 4, 4, 3, 2, 5, 3, 5, 3, 3, 1, 6, 3, 4, 7, 0, 0, 0, 4, 5, 3, 5, 5, 5, 6, 0, 5, 5, 5, 3, 4, 3, 3, 1, 1, 3, 5, 1, 5, 4, 2, 4, 5, 0, 3, 4, 7, 1, 2, 7, 2, 5, 5, 6, 6, 1, 3, 4, 5, 5, 5, 7, 1, 3, 7, 4, 7, 5, 7, 3, 5, 3, 5, 2, 4, 0, 0, 0, 1, 4, 1, 1, 4, 4, 3, 7, 4, 1, 1, 3, 4, 6, 6, 6, 2, 7, 3, 3, 2, 2, 7, 7, 7, 7, 6, 7, 7, 7, 2, 6, 2, 7, 6, 4, 7, 6, 1, 2, 4, 3, 3, 3, 4, 4, 4, 7, 3, 7, 7, 3, 2, 7, 2, 7, 7, 7, 2, 1, 0, 0, 0, 0, 1, 4, 1, 4, 3, 5, 5, 1, 3, 5, 4, 5, 3, 3, 7, 5, 5, 3, 2, 6, 5, 7, 0, 2, 7, 7, 3, 2, 4, 4, 5, 7, 3, 5, 3, 3, 1, 7, 3, 4, 4, 4, 3, 7, 4, 3, 3, 

In [ ]:
import numpy as np
from sklearn import metrics
# compute contingency matrix (also called confusion matrix)
contingency_matrix = metrics.cluster.contingency_matrix(list_labels, y_pred)
# return purity
np.sum(np.amax(contingency_matrix, axis=0)) / np.sum(contingency_matrix)

0.5170821791320406

In [ ]:
from sklearn import metrics
ARI = metrics.adjusted_rand_score(list_labels, y_pred)
print(ARI)
AMI1 = metrics.adjusted_mutual_info_score(list_labels, y_pred)
print('AMI= ',AMI1)
# 基于标准化互信息指数的相似度亦为1
NMI1 = metrics.normalized_mutual_info_score(list_labels, y_pred)
print('NMI1= ',NMI1)
# 基于互信息指数的相似度不为1，不符合理论
MI = metrics.mutual_info_score(list_labels, y_pred)
print('MI= ',MI)
homogeneity=metrics.homogeneity_score(list_labels, y_pred)
print('homogeneity= ',homogeneity)
completeness=metrics.completeness_score(list_labels, y_pred)
print('completeness= ',completeness)
completeness=metrics.v_measure_score(list_labels, y_pred)
print('completeness= ',completeness)
score = metrics.adjusted_rand_score(list_labels, y_pred)
print(score)

0.003583719340914973
AMI=  0.039013325958078666
NMI1=  0.052469279715663904
MI=  0.08984534416808754
homogeneity=  0.057443126300414045
completeness=  0.04828813898334739
completeness=  0.0524692797156639
0.003583719340914973


In [ ]:
from sklearn.manifold import TSNE
tsne = TSNE()
tsne.fit_transform(corpus_embeddings) #进行数据降维
tsne = pd.DataFrame(tsne.embedding_) #转换数据格式
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei'] #用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False #用来正常显示负号
#不同类别用不同颜色和样式绘图
d = tsne[['cluster'] == 0]
plt.plot(d[0], d[1], 'r.')
d = tsne[['cluster'] == 1]
plt.plot(d[0], d[1], 'go')
d = tsne[['cluster'] == 2]
plt.plot(d[0], d[1], 'b*')
d = tsne[['cluster'] == 3]
plt.plot(d[0], d[1], 'y.')
d = tsne[['cluster'] == 4]
plt.plot(d[0], d[1], 'g+')
d = tsne[['cluster'] == 5]
plt.plot(d[0], d[1], 'bo')
d = tsne[['cluster'] == 6]
plt.plot(d[0], d[1], 'y*')
d = tsne[['cluster'] == 7]
plt.plot(d[0], d[1], 'r*')
plt.show()

KeyError: ignored

In [ ]:
from sklearn import metrics
labels_true = [0, 0, 0, 1, 1, 1]
labels_pred = [0, 0, 1, 1, 2, 2]

# 基本用法
score = metrics.adjusted_rand_score(labels_true, labels_pred)
print(score)

# 与标签名无关
labels_pred = [5, 5, 0, 0, 7, 7]
score = metrics.adjusted_rand_score(labels_true, labels_pred)
print(score)

# 具有对称性
score = metrics.adjusted_rand_score(labels_pred, labels_true)
print(score)

# 接近 1 最好
labels_pred = labels_true[:]
score = metrics.adjusted_rand_score(labels_true, labels_pred)
print(score)

# 独立标签结果为负或者接近 0
labels_true = [0, 1, 2, 0, 3, 4, 5, 1]
labels_pred = [1, 1, 0, 0, 2, 2, 2, 2]
score = metrics.adjusted_rand_score(labels_true, labels_pred)
print(score)

0.24242424242424246
0.24242424242424246
0.24242424242424246
1.0
-0.12903225806451613


In [ ]:
with open("/content/bert_finetune390_cls_kmeans_test.txt", 'r') as f:
  for line in f:
    line = line.replace(",","")
    line = line.replace("[","")
    labels1 = line.replace("]","")
#print(labels1)
#print(true_labels)
#labels1 = kn_pre[:1083]
c1 = 0
c2 = 0
c3 = 0
c4 = 0
c5 = 0
c6 = 0
c7 = 0
c8 = 0
for i in range(391,len(labels1)):
  if(labels1[i]=='0' and true_labels[i]=='1'):
    c1 += 1
  if(labels1[i]=='0' and true_labels[i]=='2'):
    c2 += 1
  if(labels1[i]=='0' and true_labels[i]=='3'):
    c3 += 1
  if(labels1[i]=='0' and true_labels[i]=='4'):
    c4 += 1
  if(labels1[i]=='0' and true_labels[i]=='5'):
    c5 += 1
  if(labels1[i]=='0' and true_labels[i]=='6'):
    c6 += 1
  if(labels1[i]=='0' and true_labels[i]=='7'):
    c7 += 1
  if(labels1[i]=='0' and true_labels[i]=='8'):
    c8 += 1
print(c1,c2,c3,c4,c5,c6,c7,c8)

9 5 5 3 7 60 20 6


In [ ]:
M_aggregate = [[159,0,4,0,28,0,0,0],
         [2,57,122,0,0,0,0,0],
         [0,0,0,0,0,36,66,0],
         [0,0,0,0,0,0,17,0],
         [29,0,0,0,155,0,0,0],
         [0,122,4,0,0,39,3,0],
         [61,0,116,0,0,0,0,0],
         [0,0,0,19,0,0,0,0]]
m_i = [191,181,102,17,184,168,177,19]
m = 1039

In [ ]:
M_aggregate = [[3,4,9,0,19,104,32,9],
         [2,12,17,6,24,106,27,13],
         [0,13,30,3,25,113,38,15],
         [3,3,4,4,5,45,10,3],
         [8,3,8,3,5,60,9,5],
         [8,2,3,0,0,18,2,3],
         [11,0,0,0,1,8,1,0],
         [0,20 ,35 ,7 ,12, 102, 36, 12]]
m_i = [180,207,237,77,101,36,21,224]
m = 1039

In [ ]:
M_aggregate = [[9,5,5,3,7,60,20,6],
[0,7,14,6,23,89,22,14],
[0,11,23,3,10,66,23,7],
[10,0,0,0,1,6,1,0],
[6,2,1,1,0,11,1,3],
[1,1,4,3,5,51,10,3],
[0,12,17,5,16,76,36,11],
[3,2,13,0,25,80,26,11]]
m_i = [155,175,143,18,25,78,173,160]
m = 887

In [ ]:
M_aggregate = [[49,25,51,0,38,9,13,0],
         [51,69,62,0,38,16,9,0],
         [15,16,17,1,8,9,7,0],
         [15,6,8,0,13,4,2,0],
         [52,39,67,0,24,9,5,0],
         [69,18,41,0,62,6,3,0],
         [0,2,0,12,0,8,3,0],
         [0,4,0,6,0,14,44,0]]
m_i = [185,245,73,48,196,195,25,68]
m = 1083

In [ ]:
import math
e_i = [0 for x in range(0,8)]
p_i = [0 for x in range(0,8)]
for i in range(0,8):
	wr_line_part = ","
	for j in range(0,8):
		wr_line_part += str(M_aggregate[i][j]) + ','
		p_i_j = M_aggregate[i][j]*1.0/m_i[i]  + 0.00000001
		#print (p_i_j)
		e_i[i] += 0 - p_i_j*math.log2(p_i_j)
		if (p_i[i] < p_i_j):
			p_i[i] = p_i_j
	#print (e_i[i])
	print (p_i[i])

e = 0
p = 0
for i in range(0,8):
	e += m_i[i]/m*e_i[i]
	p += m_i[i]/m*p_i[i]

#print(e)
print(p)

0.38709678419354837
0.5085714385714286
0.46153847153846156
0.5555555655555556
0.44000001
0.6538461638461539
0.4393063683815029
0.50000001
0.4994363125930101


Plan3

In [ ]:
! python -m pip install --upgrade pip --quiet
! pip install spacy --quiet
! pip3 install spacy-transformers --quiet
! python -m spacy download en_trf_bertbaseuncased_lg --quiet

In [ ]:
! python -m spacy download en_trf_bertbaseuncased_lg

In [ ]:
!pip install -U pip setuptools wheel
!pip install -U spacy
!python -m spacy download en_core_web_sm

In [ ]:
!python -m spacy download en_trf_bertbaseuncased_lg

In [ ]:
#Load bert model

import spacy
nlp = spacy.load("en_core_web_sm")

#nlp = en_trf_bertbaseuncased_lg.load()

# Utility function for generating sentence embedding from the text
def get_embeddinngs(text):
    return nlp(text).vector

# Generating sentence embedding from the text
data_embedding = corpus.apply(get_embeddinngs)
print(data_embedding)

In [ ]:
!python -m en_pytt_bertbaseuncased_lg info

/usr/bin/python3: No module named en_pytt_bertbaseuncased_lg.__main__; 'en_pytt_bertbaseuncased_lg' is a package and cannot be directly executed


Plan4

In [ ]:
!pip install bert-serving-server  # server
!pip install bert-serving-client



In [ ]:
!bert-serving-start -model_dir /content/bert/ -num_worker=4

In [ ]:
!conda create -n test python=3.7.6
!conda activate test
!pip install tensorflow==1.15.0
!pip install bert-serving-server

In [ ]:
!bert-serving-start -model_dir /content/bert/ -num_worker=4

Plan5

In [ ]:
!pip install bert

  Created wheel for bert: filename=bert-2.2.0-cp37-none-any.whl size=3755 sha256=c8e7043d89a65695df1327aeb804dc9c235b19d568ccccce7540fe7e72b2df4a
  Stored in directory: /root/.cache/pip/wheels/fe/71/b7/941459453bd38e5d97a8c886361dee19325e9933c9cf88ad46
  Created wheel for erlastic: filename=erlastic-2.0.0-cp37-none-any.whl size=6787 sha256=69137741cb4a83ab79f8ab90ca0f219cc90a2db9fecd49f6498a4734f7153b50
  Stored in directory: /root/.cache/pip/wheels/02/62/46/93c713a5f061aeeb4f16eb6bf5ee798816e6ddda70faa78e69
Successfully built bert erlastic


In [ ]:
!git clone https://github.com/google-research/bert

Cloning into 'bert'...
remote: Enumerating objects: 340, done.
remote: Total 340 (delta 0), reused 0 (delta 0), pack-reused 340
Receiving objects: 100% (340/340), 328.28 KiB | 1.74 MiB/s, done.
Resolving deltas: 100% (182/182), done.


In [ ]:
cd /content/

/content


In [ ]:
!echo 'Who was Jim Henson ? ||| Jim Henson was a puppeteer' > /content/input.txt

In [ ]:
!pip install tensorflow==1.13.1

     |████████████████████████████████| 92.6MB 75kB/s 
     |████████████████████████████████| 3.2MB 46.5MB/s 
     |████████████████████████████████| 51kB 7.3MB/s 
     |████████████████████████████████| 368kB 45.6MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [ ]:
!python /content/bert/extract_features.py \
  --input_file=/content/input.txt \
  --output_file=/content/output.json \
  --vocab_file=/content/vocab.txt \
  --bert_config_file=/content/bert_config.json \
  --init_checkpoint=/content/saved_weights.pt \
  --layers=-1,-2,-3,-4 \
  --max_seq_length=128 \
  --batch_size=8

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or 

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import os

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

nonstop_text = []
f = open("/content/longreviews_sentences.txt", "r")
for paragraph in f:
	nonstop_text.append(paragraph)



vectorizer = TfidfVectorizer()
vectorizer.fit(nonstop_text)
text = vectorizer.transform(nonstop_text)

#find_k(text, 40)

clusters = KMeans(n_clusters = 8).fit_predict(text)

In [ ]:
from sklearn.cluster import Birch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import os

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
vectorizer = TfidfVectorizer()
vectorizer.fit(nonstop_text)
text = vectorizer.transform(nonstop_text)

ss = Birch(branching_factor=10, n_clusters = 8, threshold=0.5,compute_labels=True)
birch_pre = ss.fit_predict(text)
print(birch_pre)

[3 3 0 ... 7 3 0]


In [ ]:
import hdbscan
from sklearn.cluster import Birch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import os

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
vectorizer = TfidfVectorizer()
vectorizer.fit(nonstop_text)
text = vectorizer.transform(nonstop_text)

cluster = hdbscan.HDBSCAN(min_cluster_size=8,metric='euclidean',cluster_selection_method='eom').fit(text)
cluster_assignment = cluster.labels_
print(cluster_assignment)

[1 1 1 ... 1 1 1]


In [ ]:
import sklearn
from sklearn import metrics
print(metrics.calinski_harabaz_score(text.toarray(),cluster_assignment))
print(metrics.silhouette_score(text.toarray(),cluster_assignment, metric='euclidean'))
#sklearn.metrics.davies_bouldin_score(text.toarray(),cluster_assignment)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function calinski_harabaz_score is deprecated; Function 'calinski_harabaz_score' has been renamed to 'calinski_harabasz_score' and will be removed in version 0.23.
  warnings.warn(msg, category=FutureWarning)


1.8983622656031272
0.010699355252069958


In [ ]:
y_pred = clusters[:1083]

In [ ]:
import numpy as np
from sklearn import metrics
# compute contingency matrix (also called confusion matrix)
contingency_matrix = metrics.cluster.contingency_matrix(list_labels, y_pred)
# return purity
np.sum(np.amax(contingency_matrix, axis=0)) / np.sum(contingency_matrix)

0.5133887349953832

In [ ]:
from sklearn import metrics
ARI = metrics.adjusted_rand_score(list_labels, y_pred)
print(ARI)
AMI1 = metrics.adjusted_mutual_info_score(list_labels, y_pred)
print('AMI= ',AMI1)
# 基于标准化互信息指数的相似度亦为1
NMI1 = metrics.normalized_mutual_info_score(list_labels, y_pred)
print('NMI1= ',NMI1)
# 基于互信息指数的相似度不为1，不符合理论
MI = metrics.mutual_info_score(list_labels, y_pred)
print('MI= ',MI)
homogeneity=metrics.homogeneity_score(list_labels, y_pred)
print('homogeneity= ',homogeneity)
completeness=metrics.completeness_score(list_labels, y_pred)
print('completeness= ',completeness)
completeness=metrics.v_measure_score(list_labels, y_pred)
print('completeness= ',completeness)
score = metrics.adjusted_rand_score(list_labels, y_pred)
print(score)

0.0040488969112450245
AMI=  0.03811098652640065
NMI1=  0.05141087191665908
MI=  0.08899456315271898
homogeneity=  0.0568991746713972
completeness=  0.04688819458453334
completeness=  0.05141087191665908
0.0040488969112450245
